# Generated by Django 5.1.3 on 2024-11-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Joinee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=12)),
                ('stepined', models.IntegerField()),
            ],
        ),
    ]
